export interface Customer {
  custType: string;
  country: string;
  custRelationId: number;
  relationName: string;
  cif_No: string;
  status: boolean;
  cust_Type: number;
  categoryId: number;
  salut: string;
  sex_Cd: boolean;
  birthday: Date | string;
  dateOfBirth: string;
  f_Name: string;
  m_Name: string;
  l_Name: string;
  cust_Name: string;
  short_Name: string;
  comp_Code: string;
  pass_No: string;
  pass_I_Dt: Date | string;
  pass_I_Plc: string;
  pass_I_By: string;
  pass_E_Dt: string;
  pass_No2: string;
  pass_I_Dt2: Date | string;
  pass_I_Plc2: string;
  res_Add_1: string;
  res_Add_2: string;
  res_Add_3: string;
  res_Add_4: string;
  res_City: string;
  res_Cntry_Cd: string;
  leg_Add_1: string;
  leg_Add_2: string;
  leg_Add_3: string;
  leg_Add_4: string;
  leg_City: string;
  leg_Cntry_Cd: string;
  tradingAddress: string;
  tradingAddress2: string;
  phone_1: string;
  phone_2: string;
  fax: string;
  email_Id: string;
  mail_To: string;
  emp_Code: string;
  isStaff: boolean;
  isVIP: boolean;
  vipText: string;
  tax_St: string;
  tax_Cd: string;
  co_Rep_Name: string;
  co_Rep_Position: string;
  co_Rep_AuthorityNo: string;
  co_BRN_TaxCode: string;
  co_BRN_FirstDate: Date | string;
  co_BRN_LastChange: number;
  co_BRN_LastDate: Date | string;
  co_BRN_Plc: string;
  bankAccount: string;
  bankBrach: string;
  bankName: string;
  mkr_St: boolean;
  mkr_Cd: string;
  mkr_Dt: Date | string;
  aut_Cd: string;
  aut_Dt: Date | string;
  open_Dt: Date | string;
  closing_Dt: Date | string;
  isOrder: boolean;
  isContract: boolean;
  isAccount: boolean;
  userId: string;
  sysDate: Date | string;
  pass_I_Plc_EN: string;
  res_Add_1_EN: string;
  leg_Add_1_EN: string;
  order_Note: string;
  workStatusId: string;
}

export interface Booking {
  bookingId: number;
  cif_No: string;
  open_Type: number;
  roomCd: string;
  custName: string;
  phone: string;
  email: string;
  address: string;
  idCard_No: string;
  idCard_Dt: string;
  idCard_Plc: string;
  depositAmt: number;
  amount: number;
  agencyId: number;
  agentCd: string;
}

export interface MetaDocument {
  metaId: number;
  metaNote: string;
  metaName: string;
  metaUrl: string;
  docType: string;
  imageAndVideo: any;
}
