export interface StockDiaries {
    idDetail?: string;
    id: string;
    kieudat: number;
    store_id: string;
    order_id: string;
    supplier_id: string;
    customer_id: string;
    stock_no: string;
    stock_date: Date;
    payment_date: Date;
    staff_id: string;
    reason: number;
    stock_id: string;
    coefficient: number;
    is_fixed_payment: number;
    is_move_to_accounting: number;
    account_id: number;
    status: number;
    created: Date;
    created_by: string;
    updated: Date;
    updated_by: string;
    discount_amount?: number;
    total_amount_on_product?: number;
    total_remain_amount?: number;
    total_vat_5: number,
    total_vat_10: number,
}

export interface StockDiariesDetail {
    id: string;
    stock_diary_id: string;
    parent_product_id: string;
    unit_parent: any,
    promotion_parent: any
    product_id: string;
    bar_code: string;
    unit_id: string;
    quantity: number;
    price: number;
    amount: number;
    tax_rate: number;
    tax_amount: number;
    discount: number;
    discount_amount: number;
    remain_amount: number;
    expire_date: Date;
    inc: number;
    product_name: string;
    unit_name: string;
    internal_code: string;
    promotion_id: string;
    promotion_code: string;
    discount_on_bill?: number;
    discount_on_bill_amount?: number;
    before_vat_amount?: number;
    price_after_vat?: number;
    gift: number;
    stock_quantity: number,
    stock_internal_quantity: number,
    previous_month_quantity: number,
    previous_month_internal_quantity: number,
    valid?: boolean;
    reason?: number;
    origin_quantity?: number;
    order_quantity?: number;
    open_discount: number,
    open_discount_amount: number,
    real_price?: number;
    coefficient?: number;
}
